feat: allow users to view past generations
RocketChat/Apps.AI.GIF pull request #12
Opened 2024-07-04 14:58 UTC by AmanNegi

## Description

Allows users to view past generations. Implemented using `IPersistence` and storing the generations using multiple associations. The generations are uniquely stored for each user, and can be viewed by passing `h` or `history` as the first parameter to the `gen-gif` command.

### Preview

https://github.com/RocketChat/Apps.AI.GIF/assets/37607224/a8db8f13-a3d2-4c08-a7f1-91bd8786d183

2024-07-05 07:59 UTC, Nabhag8848 commented
@AmanNegi Merge Conflicts

2024-07-07 04:51 UTC, AmanNegi commented
@Nabhag8848 I have fixed the merge conflicts, could you please look into this.

2024-07-08 14:16 UTC, Nabhag8848 requested changes
@AmanNegi

2024-07-08 14:16 UTC, Nabhag8848 commented on src/persistence/GenerationPersistence.ts
> +        ]);
@AmanNegi this associations is repeating in entire file, can you make this association to initialise when we create an instance of this ? under constructor make the member of classs as private.

2024-07-08 16:38 UTC, Nabhag8848 approved these changes
LGTM @AmanNegi

2024-07-08 16:38 UTC, merged