feat: enable GIF preview and add Action Buttons
RocketChat/Apps.AI.GIF pull request #16
Opened 2024-07-15 03:43 UTC by AmanNegi

## Description :memo: 

- Implement UIKit components and Buttons to provide user with an option to preview the GIF before sending to the channel.
- The user can decide to re-generate the GIF or send the generated GIF to the channel.

> Fixes: #15 

## Demo :video_camera: 

https://github.com/user-attachments/assets/e491ddbb-3263-4c6f-8e3a-4cb0b88462c7

2024-07-15 03:43 UTC, AmanNegi commented
@Nabhag8848 Could you please review this and let me know if any changes are required.

2024-07-21 08:52 UTC, Nabhag8848 commented
@AmanNegi  merge conflicts

2024-07-21 14:06 UTC, AmanNegi commented
> @AmanNegi merge conflicts

Fixed the merge conflicts. :heavy_check_mark:

2024-07-22 12:49 UTC, Nabhag8848 requested changes
@AmanNegi

2024-07-22 12:49 UTC, Nabhag8848 commented on src/handlers/ExecuteBlockActionHandler.ts
> +            } else if (
@AmanNegi use switch instead.

2024-07-22 12:49 UTC, Nabhag8848 commented on src/lib/RedefinePrompt.ts
> +            logger.log("PromptVariationCommand.preview", response.data);
@AmanNegi

2024-07-22 12:49 UTC, Nabhag8848 commented on src/handlers/PreviewerHandler.ts
> +        }
@AmanNegi What if the res is not there how user will get to know ? as discussed.

2024-07-22 15:48 UTC, AmanNegi commented
@Nabhag8848 I have made the requested changes. Could you please take a look!

2024-07-24 12:11 UTC, Nabhag8848 approved these changes
@AmanNegi LGTM !

2024-07-24 12:12 UTC, merged