feat: add pagination in history
RocketChat/Apps.AI.GIF pull request #18
Opened 2024-07-15 11:52 UTC by AmanNegi

## Description :notebook: 

- Allow users to view and store more than 10 generations.
- The user can simply pass the page number along with the command as:

 	`gen-gif h <page>`

> Fixes: #17 

## Demo :video_camera: 

https://github.com/user-attachments/assets/b5650e79-30b3-4907-a402-18113f5490bc

2024-07-15 11:52 UTC, AmanNegi commented
@Nabhag8848 Could you please review the PR and let me know if any changes are required.

2024-07-22 13:06 UTC, Nabhag8848 requested changes
@AmanNegi

2024-07-22 13:06 UTC, Nabhag8848 commented on src/endpoints/GifStatusUpdateEndpoint.ts
> +        const uuid = Math.floor(Date.now() * Math.random());
@AmanNegi  https://github.com/RocketChat/Apps.Notion/blob/main/src/helper/uuid.ts

2024-07-22 13:06 UTC, Nabhag8848 commented on src/persistence/GenerationPersistence.ts
> +        console.log(page, list.length, list);
@AmanNegi

2024-07-24 12:12 UTC, Nabhag8848 commented
@AmanNegi conflicts

2024-07-25 04:35 UTC, AmanNegi commented
@Nabhag8848 Fixed all merge conflicts!

2024-07-25 06:44 UTC, Nabhag8848 commented
- @AmanNegi what happens if  **/gen-gif h**  also 
- what if the **/gen-gif h <random-value>** random-value page doesn't exist ? also 
- what if **/gen-gif h <some-text>** ? 

does this cases are handled ?

2024-07-25 06:59 UTC, AmanNegi commented
If we simply use `/gen-gif h` without providing the page, by default it renders the first page.

If we provide an out of bounds page, no preview is shown suggesting that this page doesn't exist. 

(Ps: currently preview titles don't show up otherwise we could provide user with a message in preview heading itself. I have created an issue for that as well).

2024-07-25 12:38 UTC, Nabhag8848 commented
@AmanNegi 

> [!CAUTION]
> If we provide an out of bounds page, no preview is shown suggesting that this page doesn't exist.

> [!TIP]
> For now send notifications to room (which only user can see) for letting user know that.

> [!IMPORTANT]
> What if /gen-gif h "helloWorld" ? does it handles the provided page is number.

2024-07-26 02:36 UTC, AmanNegi commented
> "For now send notifications to room (which only user can see) for letting user know that."

Okay for pages which don't have an item, we will notify the user with a message "No items to show on page 1".

> "What if /gen-gif h "helloWorld" ? does it handles the provided page is number."

Yes it does handle that case and by returns the items on page 1 itself.

2024-07-27 06:59 UTC, Nabhag8848 commented
> > "For now send notifications to room (which only user can see) for letting user know that."
> 
> Okay for pages which don't have an item, we will notify the user with a message "No items to show on page 1".
> 
> > "What if /gen-gif h "helloWorld" ? does it handles the provided page is number."
> 

- For pages which don't have item - convey that there isn't any gif more than x number. so to me it makes more sense to say No page exist and to convey some message that there is only max this much page. 

> Yes it does handle that case and by returns the items on page 1 itself.

- does it gives the warning notification about that, as page is just number we have return most recent page items ?

2024-07-28 03:09 UTC, AmanNegi commented
I have successfully fixed the above issues, and now the app shows valid error messages (for each case covered above).


#### Demo


https://github.com/user-attachments/assets/ecda7454-d213-4bd7-9d0d-80e63f877c88

2024-07-28 17:05 UTC, Nabhag8848 approved these changes
@AmanNegi  LGTM !

2024-07-28 17:05 UTC, Nabhag8848 commented on src/handlers/PreviewerHandler.ts
> -                this.modify,
@AmanNegi Why this has been removed ? this will break the changes we made in previous PR right ?

2024-07-28 17:06 UTC, merged