feat: enhance user query using LLM
RocketChat/Apps.AI.GIF pull request #8
Opened 2024-06-16 17:37 UTC by AmanNegi

## Description

- Implement LLM as NLP to improve the user query. The LLM provides with 4 different variations of the query. The user can click on any of the variation to use as the prompt for GIF generation.
- Also provides a mock function for testing LLM functionality on LLM-inacessible servers.

> Fixes: #4

2024-06-27 08:30 UTC, Nabhag8848 requested changes
@AmanNegi added comments, Also can you share demo again here around.
1. What happens in this case when the LLM doesn't response.
2. What happens when we don't get the response from the model Itself.

2024-06-27 08:30 UTC, Nabhag8848 commented on src/commands/GenGifCommand.ts
> +
Can you make a seperate class / service for debouncing + make this typesafe and add comments more comments.

2024-06-27 11:17 UTC, AmanNegi commented
> @AmanNegi added comments, Also can you share demo again here around.
> 
>     1. What happens in this case when the LLM doesn't response.
> 
>     2. What happens when we don't get the response from the model Itself.

In these cases where the LLM/Model doesn't response for too long, the HTTP request will expire and it will throw an error. For the end user he would not know about the error, and he wouldn't be getting anything on the preview. 

Ps: Currently I am not handling the reject promise case, I'll do it in the next commit.

> The error can be identified through logs, and alternatively we could send the error message as notification to the user as well. Let me know if we expect that behavior.

2024-06-27 13:17 UTC, AmanNegi commented
@Nabhag8848 I have made the request changes. In the implementation in case the sever doesn't respond or there is any other kind of error from server side, the user will be notified via a message(visible to self).

#### Demo

https://github.com/RocketChat/Apps.AI.GIF/assets/37607224/8b629f3b-eb11-4236-a163-51a45d730479

2024-06-28 06:42 UTC, Nabhag8848 approved these changes
LGTM 🚀

2024-06-28 06:43 UTC, merged